[project]
name = "telegram-autobot"
version = "1.0"
description = "Telegram auto-reply bot"
requires-python = ">=3.10"

dependencies = [
    "python-telegram-bot==20.7"
]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"